name: Publish Storybook documentation from PR

permissions:
  contents: read
  deployments: write
on:
  # Must be run for pushes to associate deployment with PR. Otherwise docs link is not shown.
  push:
    # Required to avoid triggering on automatic release tags.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
    branches-ignore:
      - main
      - "release-**"
      - "dependabot/**"

jobs:
  publish:
    name: Publish PR Storybook docs to AWS
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: core
    steps:
      - name: Start Storybook deployment
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        id: deployment
        with:
          step: start
          env: Storybook documentation for branch ${{ github.ref_name }}
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook docs
        run: npm run build:storybook
      - name: Copy storybook docs to S3 bucket
        run: aws s3 sync storybook-static s3://${{ vars.AWS_S3_BUCKET_NAME }}/core/branch/${{ github.ref_name }} --delete --cache-control max-age=5
      - name: Finish deployment
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: https://fudis.funidata.fi/core/branch/${{ github.ref_name }}/index.html
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
